apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication
  template:
    metadata:
      labels:
        app: communication
    spec:
      containers:
      - name: communication
        image: devopskpi.azurecr.io/communication:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: Redis__ConnectionString
          value: redis:6379
        - name: BasePath
          value: /api
